{{- if not .Values.skipHeadlessService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
    - name: gossip
      port: {{ .Values.cluster.gossip.port }}
      protocol: TCP
      targetPort: {{ .Values.cluster.gossip.port }}
{{- end }}



