apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mattermost.fullname" . }}
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mattermost.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mattermost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mattermost.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mattermost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: mattermost
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        - name: gossip
          containerPort: {{ .Values.mattermost.config.ClusterSettings.GossipPort }}
          protocol: TCP
        env:
        - name: MM_CACHESETTINGS_CACHE_TYPE
          value: "redis"
        - name: MM_CACHESETTINGS_REDIS_ADDRESS
          value: "49.213.89.95:6379"
        - name: MM_CACHESETTINGS_REDIS_PASSWORD
          value: "W484oYdQwW2Voq25XgL2DtJPW8pFkTD2NAGQj7"
        - name: MM_CACHESETTINGS_REDIS_DB
          value: "0"
        - name: MM_SQLSETTINGS_DRIVERNAME
          value: {{ .Values.mattermost.config.SqlSettings.DriverName | quote }}
        - name: MM_SQLSETTINGS_DATASOURCE
          value: {{ include "mattermost.postgresql.datasource" . | quote }}
        # - name: MM_CONFIG
        #   value: "/mattermost/config/config.json"
        - name: MM_CONFIG
          value: {{ include "mattermost.postgresql.datasource" . | quote }}
        - name: MM_CLUSTERSETTINGS_ENABLE
          value: {{ ternary "true" "false" .Values.mattermost.config.ClusterSettings.Enable | quote }}
        - name: MM_CLUSTERSETTINGS_CLUSTERNAME
          value: {{ .Values.mattermost.config.ClusterSettings.ClusterName | quote }}
        - name: MM_CLUSTERSETTINGS_BINDADDRESS
          value: {{ .Values.mattermost.config.ClusterSettings.BindAddress | quote }}
        - name: MM_CLUSTERSETTINGS_GOSSIPPORT
          value: {{ .Values.mattermost.config.ClusterSettings.GossipPort | quote }}
        - name: MM_CLUSTERSETTINGS_LEADERELECTIONMODE
          value: {{ .Values.mattermost.config.ClusterSettings.LeaderElectionMode | quote }}
        - name: MM_CLUSTERSETTINGS_LEADERELECTIONK8SNAMESPACE
          value: {{ include "mattermost.lease.namespace" . | quote }}
        - name: MM_CLUSTERSETTINGS_LEADERELECTIONK8SLEASENAME
          value: {{ include "mattermost.lease.name" . | quote }}
        - name: MM_HIGHAVAILABILITYSETTINGS_ENABLE
          value: {{ ternary "true" "false" .Values.mattermost.config.HighAvailabilitySettings.Enable | quote }}
        - name: MM_HIGHAVAILABILITYSETTINGS_READONLYCONFIG
          value: {{ ternary "true" "false" .Values.mattermost.config.HighAvailabilitySettings.ReadOnlyConfig | quote }}
        - name: MM_SERVICESETTINGS_LISTENADDRESS
          value: {{ .Values.mattermost.config.ServiceSettings.ListenAddress | quote }}
        - name: MM_SERVICESETTINGS_SITEURL
          value: {{ .Values.mattermost.config.ServiceSettings.SiteURL | quote }}
        - name: MM_LOGSETTINGS_ENABLECONSOLE
          value: {{ ternary "true" "false" .Values.mattermost.config.LogSettings.EnableConsole | quote }}
        - name: MM_LOGSETTINGS_CONSOLELEVEL
          value: {{ .Values.mattermost.config.LogSettings.ConsoleLevel | quote }}
        - name: MM_LOGSETTINGS_CONSOLEJSON
          value: {{ ternary "true" "false" .Values.mattermost.config.LogSettings.ConsoleJson | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config
          mountPath: /mattermost/config
        {{- if .Values.persistence.enabled }}
        - name: storage
          mountPath: {{ .Values.mattermost.config.FileSettings.Directory }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/v4/system/ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v4/system/ping
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: {{ include "mattermost.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "{{ (index .Values.persistence.accessModes 0) }}" ]
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}

